const $=s=>document.querySelector(s);
const loginView=$('#loginView'),dashboardView=$('#dashboardView'),loginForm=$('#loginForm'),loginError=$('#loginError');
const blockStart=$('#blockStart'),blockEnd=$('#blockEnd'),blockDate=$('#blockDate'),calendarFocus=$('#calendarFocus');
let records=[];
const pad=n=>String(n).padStart(2,'0');
function formatTime(m){const h=Math.floor(m/60)%24,s=h>=12?'PM':'AM',dh=(h%12)||12;return `${dh}:${pad(m%60)} ${s}`}
function dateKey(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function money(n){return `$${Number(n||0).toFixed(2)}`}
function dateTimeLabel(iso){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(iso))}
async function api(url,opts){const r=await fetch(url,opts);const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
function populateTimes(){for(let m=0;m<1440;m+=30){const o=document.createElement('option');o.value=formatTime(m);o.textContent=formatTime(m);o.dataset.minutes=m;blockStart.appendChild(o)} updateBlockEnd();}
function updateBlockEnd(){blockEnd.innerHTML='<option value="">Choose end</option>';const s=Number(blockStart.selectedOptions[0]?.dataset.minutes);if(!Number.isFinite(s))return;for(let m=s+30;m<=s+720;m+=30){const o=document.createElement('option');o.value=formatTime(m);o.textContent=`${formatTime(m)}${m>=1440?' (next day)':''}`;o.dataset.minutes=m;blockEnd.appendChild(o)}}
async function checkSession(){try{const d=await api('/api/admin/me');showDashboard(d.username)}catch{showLogin()}}
function showLogin(){loginView.classList.remove('hidden');dashboardView.classList.add('hidden')}
function showDashboard(username){loginView.classList.add('hidden');dashboardView.classList.remove('hidden');$('#adminUser').textContent=username;const today=dateKey(new Date());blockDate.value=today;calendarFocus.value=today;loadRecords();renderWeek(today);renderDay(today)}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.textContent='';try{const d=await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#username').value,password:$('#password').value})});showDashboard(d.username)}catch(err){loginError.textContent=err.message}});
$('#logoutBtn').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST'});showLogin()});
async function loadRecords(){try{const d=await api('/api/admin/bookings');records=d.bookings||[];renderStats();renderTable();}catch(err){console.error(err)}}
function renderStats(){const live=records.filter(r=>r.status!=='cancelled');$('#statTotal').textContent=live.length;$('#statConfirmed').textContent=live.filter(r=>r.status==='confirmed').length;$('#statQuotes').textContent=live.filter(r=>r.status==='quote').length;$('#statHolds').textContent=live.filter(r=>r.status==='hold').length}
function renderTable(){const filter=$('#statusFilter').value;const body=$('#recordsBody');body.innerHTML='';records.filter(r=>filter==='all'||r.status===filter).forEach(r=>{const tr=document.createElement('tr');const actions=r.status==='quote'?`<button class="mini-btn" data-action="confirm" data-id="${r.id}">Confirm</button><button class="mini-btn danger" data-action="cancel" data-id="${r.id}">Decline</button>`:r.status==='confirmed'?`<button class="mini-btn danger" data-action="cancel" data-id="${r.id}">Cancel</button>`:r.status==='blocked'?`<button class="mini-btn danger" data-action="delete" data-id="${r.id}">Unblock</button>`:r.status==='hold'?`<button class="mini-btn" data-action="confirm" data-id="${r.id}">Mark Confirmed</button><button class="mini-btn danger" data-action="cancel" data-id="${r.id}">Cancel</button>`:'';tr.innerHTML=`<td>${dateTimeLabel(r.startAt)}<br>→ ${new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(r.endAt))}</td><td class="customer"><strong>${esc(r.customer?.name||'—')}</strong><span>${esc(r.customer?.phone||'')}</span></td><td>${esc(r.service||'')}</td><td>${r.status==='quote'?'Inquiry':money(r.total)}</td><td>${money(r.deposit)}</td><td><span class="status">${r.status}</span></td><td><div class="action-row">${actions}</div></td>`;body.appendChild(tr)})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#statusFilter').addEventListener('change',renderTable);
$('#recordsBody').addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const id=b.dataset.id,action=b.dataset.action;if(!confirm(action==='delete'?'Unblock this time?':action==='cancel'?'Cancel this record?':'Mark this as confirmed?'))return;try{if(action==='delete')await api('/api/admin/bookings/'+id,{method:'DELETE'});else await api('/api/admin/bookings/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:action==='confirm'?'confirmed':'cancelled'})});await loadRecords();renderWeek(calendarFocus.value);renderDay(calendarFocus.value)}catch(err){alert(err.message)}});
$('#blockForm').addEventListener('submit',async e=>{e.preventDefault();$('#blockMessage').textContent='';try{const end=Number(blockEnd.selectedOptions[0]?.dataset.minutes);await api('/api/admin/block',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:blockDate.value,start_time:blockStart.value,end_minutes:end,note:$('#blockNote').value})});$('#blockMessage').textContent='Time blocked successfully.';$('#blockNote').value='';await loadRecords();renderWeek(blockDate.value);renderDay(blockDate.value)}catch(err){$('#blockMessage').textContent=err.message}});
blockStart.addEventListener('change',updateBlockEnd);
calendarFocus.addEventListener('change',()=>{renderWeek(calendarFocus.value);renderDay(calendarFocus.value)});
$('#prevWeek').addEventListener('click',()=>shiftWeek(-7));
$('#nextWeek').addEventListener('click',()=>shiftWeek(7));
$('#todayWeek').addEventListener('click',()=>{const t=dateKey(new Date());calendarFocus.value=t;renderWeek(t);renderDay(t)});
function localDate(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function shiftWeek(days){const d=localDate(calendarFocus.value||dateKey(new Date()));d.setDate(d.getDate()+days);const key=dateKey(d);calendarFocus.value=key;renderWeek(key);renderDay(key)}
function startOfWeek(date){const d=localDate(date);const day=d.getDay();d.setDate(d.getDate()-day);return d}
function minsOfDateTime(iso){const d=new Date(iso);return d.getHours()*60+d.getMinutes()}
function shortDate(d){return new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(d)}
function niceTime(mins){const m=((mins%1440)+1440)%1440;const h=Math.floor(m/60),mm=m%60;return `${(h%12)||12}:${pad(mm)} ${h>=12?'PM':'AM'}`}
function weekDateKeys(anchor){const d=startOfWeek(anchor);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return dateKey(x)})}
function recordsForDate(date){return records.filter(r=>r.status!=='cancelled' && r.startAt.slice(0,10)<=date && r.endAt.slice(0,10)>=date).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt))}
function dayBusyIntervals(date){return recordsForDate(date).map(r=>{const dayStart=new Date(`${date}T00:00:00`);const dayEnd=new Date(`${date}T23:59:59.999`);let s=new Date(r.startAt),e=new Date(r.endAt);if(s<dayStart)s=dayStart;if(e>dayEnd)e=dayEnd;return {start:s.getHours()*60+s.getMinutes(),end:e.getHours()*60+e.getMinutes()+ (e.getSeconds()>0?1:0),status:r.status,record:r}}).filter(x=>x.end>x.start).sort((a,b)=>a.start-b.start)}
function freeWindows(date){const busy=dayBusyIntervals(date);const out=[];let cursor=0;for(const b of busy){if(b.start>cursor)out.push({start:cursor,end:b.start});cursor=Math.max(cursor,b.end)}if(cursor<1440)out.push({start:cursor,end:1440});return out}
function renderWeek(anchor){if(!anchor)return;const dates=weekDateKeys(anchor);const first=localDate(dates[0]),last=localDate(dates[6]);$('#weekLabel').textContent=`${shortDate(first)} – ${shortDate(last)}`;const cal=$('#weekCalendar');cal.innerHTML='';const today=dateKey(new Date());dates.forEach(date=>{const d=localDate(date), busy=dayBusyIntervals(date), free=freeWindows(date);const col=document.createElement('div');col.className='week-day'+(date===today?' today':'');let events='';busy.forEach(b=>{const r=b.record;const label=r.status==='blocked'?'BLOCKED':r.status==='confirmed'?'BOOKED':r.status==='hold'?'HOLD':'QUOTE';const name=r.status==='blocked'?(r.adminNote||r.pickup||'Unavailable'):(r.customer?.name||r.service||'Booking');events+=`<div class="week-event ${esc(r.status)}"><div><strong>${label}</strong><span>${niceTime(b.start)} – ${niceTime(b.end)}</span></div><small>${esc(name)}</small></div>`});let opens='';free.forEach(w=>{if(w.end-w.start>=30)opens+=`<div class="open-slot"><span>OPEN</span><b>${niceTime(w.start)} – ${niceTime(w.end)}</b>${w.end-w.start>=180?'<em>3+ hr window</em>':''}</div>`});if(!events)events='<div class="empty-state">No blocked or booked times</div>';if(!opens)opens='<div class="empty-state closed">No open time</div>';col.innerHTML=`<button type="button" class="week-day-head" data-date="${date}"><span>${new Intl.DateTimeFormat('en-US',{weekday:'short'}).format(d)}</span><strong>${d.getDate()}</strong><small>${new Intl.DateTimeFormat('en-US',{month:'short'}).format(d)}</small></button><div class="day-section"><div class="section-mini-title">BLOCKED / BOOKED</div>${events}</div><div class="day-section available-section"><div class="section-mini-title">AVAILABLE</div>${opens}</div>`;cal.appendChild(col)});cal.querySelectorAll('.week-day-head').forEach(b=>b.addEventListener('click',()=>{calendarFocus.value=b.dataset.date;renderDay(b.dataset.date);renderWeek(b.dataset.date)}))}
async function renderDay(date){if(!date)return;try{const d=await api('/api/admin/bookings');const day=(d.bookings||[]).filter(r=>r.startAt.slice(0,10)===date||r.endAt.slice(0,10)===date).filter(r=>r.status!=='cancelled').sort((a,b)=>new Date(a.startAt)-new Date(b.startAt));const el=$('#daySchedule');if(!day.length){el.innerHTML='<p class="muted">No bookings or blocked times for this date.</p>';return}el.innerHTML=day.map(r=>`<div class="schedule-item"><div class="schedule-time">${new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(r.startAt))} – ${new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(r.endAt))}</div><div class="schedule-main"><strong>${esc(r.customer?.name||r.service||'Unavailable')}</strong><span>${esc(r.service||'')} ${r.customer?.phone?' · '+esc(r.customer.phone):''}</span></div><span class="status">${esc(r.status)}</span></div>`).join('')}catch(err){$('#daySchedule').innerHTML='<p class="muted">Unable to load schedule.</p>'}}
populateTimes();checkSession();
